### ISSUE TITLE
Telugu transliteration

### ISSUE THREAD

**Issue by spandanaakella** [lakhansamani/covid-info#21]
![image](https://user-images.githubusercontent.com/83237049/116131547-60cd6e80-a681-11eb-9754-55ecb2e7e957.jpeg)

![image](https://user-images.githubusercontent.com/83237049/116131565-662ab900-a681-11eb-9af5-e3a1b88d44ac.jpeg)

**Comment by spandanaakella** [comment]
For "Clear", replace second word above with - ![image](https://user-images.githubusercontent.com/83237049/116177766-4323f780-a6c9-11eb-96b3-8a6e2d9370e2.jpeg)

**Comment by samyakbhuta** [comment]
@spandanaakella you can't submit screen shots! You have to provide the text that @lakhansamani can copy :)

**Comment by samyakbhuta** [comment]
https://github.com/lakhansamani/covid-info/blob/main/locales/en/common.json can be used to know what all translations keys are.

**Comment by spandanaakella** [comment]
Sorry about that, didn’t realize :).

Here it is -

Filter

ఫిల్టర్ చేయండి

Clear

ఫిల్టర్ తీసేయండి


 Search name, address, phone no.

   పేరు, చిరునామా, ఫోన్ నెంబర్  వెతకండి

Search a city

మీ నగరం కోసం వెతకండి

Call

కాల్ చేయండి

Private Hospital

ప్రైవేట్ ఆసుపత్రి

Copy

కాపీ చేయండి

Share

షేర్ చేయండి

Government Hospital

గవర్నమెంట్ ఆసుపత్రి

Go to maps

గూగుల్ మ్యాప్ లో చూడండి

Oxygen

ఆక్సిజన్

Remdesivir

రెండిసివిర్

Information Center

సమాచారం దొరికే స్థలం

Get information about Covid-19 hospitals, beds, oxygen, medicines, doctors
and services

కోవిడ్ -19 కి సంబంధించిన హాస్పిటల్, పడకలు, ఆక్సిజన్, మందులు, డాక్టర్స్, ఇతర
సేవలు

**Comment by lakhansamani** [comment]
@spandanaakella there are more keys that need translation.

Do check following file for the keys that needs translation
https://github.com/lakhansamani/covid-info/blob/main/locales/en/common.json

Thanks

**Comment by spandanaakella** [comment]
Hi,
Here is the updated list -

title": "COVID-19",
 శీర్షిక "కోవిడ్ -19" "information_center": "Information Center",
"సమాచార కేంద్రం ":
"సమాచారం  దొరికే స్థలం "
  "description": "Get information about COVID-19 hospitals, beds, oxygen,
medicine, doctors and other services",
"వివరం" :"కోవిడ్-19 ఆసుపత్రులు,
పడకలు,ఆక్సిజన్,  మందులు, డాక్టర్స్, ఇతర సేవల గురించి,
సమాచారం తెలుసు కోండి. "
  "filter": "Filter",
"ఫిల్టర్ చేయండి ":ఫిల్టర్ చేయండి "
  "copy": "Copy",
"కాపీ చేయండి ":"కాపీ చేయండి "
  "share": "Share",
"షేర్ చేయండి ":"షేర్ చేయండి "
  "name": "Name",
"పేరు ":"పేరు "
  "address":
 "Address",
"చిరునామా ":"చిరునామా "
  "phone": "Phone",
"ఫోన్ ":"ఫోన్ "
  "search": "Search by name, address, phone",
"వెతకండి ": "పేరు, చిరునామా, ఫోన్ ను బట్టి వెతకండి "
  "call": "Call",
" కాల్ చేయండి ":కాల్ చేయండి "
  "select_city": "Select City",
"నగరం _ఎంచుకోండి ":
"నగరం ఎంచుకోండి "
  "go_to_maps": "Go to maps",
"గూగుల్ మ్యాప్స్_ కి_ వెళ్ళండి ":"గూగుల్ మ్యాప్స్ _కి _వెళ్ళండి "
  "filter_services": "Filter Services",
"ఫిల్టర్ _సేవలు ":
"ఫిల్టర్ సేవలు "
  "apply_filter": "Apply Filter",
"ఫిల్టర్_ వాడండి ":
"ఫిల్టర్ వాడండి "
  "govt_hospital": "Government Hospital",
"గవర్నమెంట్_ హాస్పిటల్ ":
"గవర్నమెంట్ హాస్పిటల్ "
  "private_hospital": "Private Hospital",
"ప్రైవేట్_ హాస్పిటల్ ":
"ప్రైవేట్ హాస్పిటల్ "
  "oxygen": "Oxygen",
"ఆక్సిజన్ ":"ఆక్సిజన్ "
  "remdesivir": "Remdesivir",
"రెండెసివిర్ ":"రెండె సివిర్ "
  "footer_1": "We are actively gathering information about COVID-19
hospitals and services.",
"గమనిక _1" :
"మేము కోవిడ్ -19 హాస్పిటల్స్, సేవల  గురించి సమాచారం చురుకుగా
సేకరిస్తున్నాము   "
  "footer_2": "Please contribute by sending any COVID-19 related
information to",
"గమనిక _2": "కోవిడ్ -19 గురించి సమాచారం పంపి సహకరించండి "
  "clear": "Clear",
 "తీసేయండి ": "తీసేయండి " "copied_to_clipboard": "Copied to Clipboard",
"క్లిప్ బోర్డు_ కి _కాపీ చేయండి ": "క్లిప్ బోర్డు కి కాపీ చేయబడినది "
 "mobile_only_feature": "This feature is only supported on mobile browsers",
"మొబైల్ _లో _మాత్రమే ":" ఇది మొబైల్ బ్రౌజరు లో మాత్రమే
 దొరుకుతుంది "
  "not_found": "404 Not Found",
"దొరకలేదు ": "404 దొరకలేదు "
  "back": "Back"
"వెనుకకు ":
 "వెనుకకు "

Best,
Spandana
