### ISSUE TITLE
Translation for Hindi

### ISSUE THREAD

**Issue by samyakbhuta** [lakhansamani/covid-info#6]

**Comment by lakhansamani** [comment]
@samyakbhuta here is the list of available labels:
https://github.com/lakhansamani/covid-info/blob/main/locales/hi/common.json

Can you help us add the translation for Hindi in the same file?

Here is the English equivalent of it
https://github.com/lakhansamani/covid-info/blob/main/locales/en/common.json

**Comment by samyakbhuta** [comment]
👍
